# Generated by Django 5.0.1 on 2024-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_delman'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=80),
        ),
        migrations.AddField(
            model_name='deliveryman',
            name='deliveryman_name',
            field=models.CharField(default='Unknown', max_length=80),
        ),
    ]
