# Generated by Django 5.0.1 on 2024-01-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_Item_Price',
            new_name='cart_item_price',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_Plant_Quantity',
            new_name='cart_plant_quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_Status',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_Item_Price',
            new_name='order_item_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='plant_Quantity',
            new_name='plant_quantity',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='to_Review',
            new_name='to_review',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_Date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_Cost',
            new_name='payment_cost',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='receive_Method',
            new_name='receive_method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='shipping_Fee',
            new_name='shipping_fee',
        ),
    ]
